### ISSUE TITLE
Upload

### ISSUE THREAD

**Issue by zshc** [OPSnet/Gazelle#205]
I got this error when I uploaded 
```
Fatal error: Uncaught TypeError: Gazelle\Manager\TGroup::create(): Argument #2 ($releaseType) must be of type int, null given, called in /my/path/sections/upload/upload_handle.php on line 542 and defined in /my/path/app/Manager/TGroup.php:87 Stack trace: #0 /my/path/sections/upload/upload_handle.php(542): Gazelle\Manager\TGroup->create() #1 /my/path/sections/upload/index.php(18): require_once('...') #2 /my/path/gazelle.php(182): require_once('...') #3 /my/path/public/index.php(3): require_once('...') #4 {main} thrown in /my/path/app/Manager/TGroup.php on line 87
```

**Comment by sheepish-ops** [comment]
fixed in the latest dump
